[project]
name="kaggle-disaster-adaflood"
requires-python = ">= 3.10"
dependencies = [
    "torch",
    "transformers",
    "datasets",
    "pandas",
    "numpy",
    "click",
    "mlflow"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"